// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddUBGgpeouCRwTTBNoz3sPL3cI189fb0',
    appId: '1:876820605912:web:fdaae3a59af93b538b60ad',
    messagingSenderId: '876820605912',
    projectId: 'aquacatch-17d46',
    authDomain: 'aquacatch-17d46.firebaseapp.com',
    storageBucket: 'aquacatch-17d46.firebasestorage.app',
    measurementId: 'G-N3N14L6S6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-iCT83De7aueu4obApoHDMdXnStGb0U',
    appId: '1:876820605912:android:2c1555091bb9d54e8b60ad',
    messagingSenderId: '876820605912',
    projectId: 'aquacatch-17d46',
    storageBucket: 'aquacatch-17d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gD8JjRTpfchurUHxQeIncAZ_TziNUQ8',
    appId: '1:876820605912:ios:e3146067b418f1fb8b60ad',
    messagingSenderId: '876820605912',
    projectId: 'aquacatch-17d46',
    storageBucket: 'aquacatch-17d46.firebasestorage.app',
    iosBundleId: 'com.example.aquacatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gD8JjRTpfchurUHxQeIncAZ_TziNUQ8',
    appId: '1:876820605912:ios:e3146067b418f1fb8b60ad',
    messagingSenderId: '876820605912',
    projectId: 'aquacatch-17d46',
    storageBucket: 'aquacatch-17d46.firebasestorage.app',
    iosBundleId: 'com.example.aquacatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBddUBGgpeouCRwTTBNoz3sPL3cI189fb0',
    appId: '1:876820605912:web:3899f274753c9d168b60ad',
    messagingSenderId: '876820605912',
    projectId: 'aquacatch-17d46',
    authDomain: 'aquacatch-17d46.firebaseapp.com',
    storageBucket: 'aquacatch-17d46.firebasestorage.app',
    measurementId: 'G-YPMH71GV8W',
  );
}
